---
  - hosts: database
    become: true
    tasks:
      - name: Install MySQL DB
        apt: name=mysql-server state=present update_cache=yes 
            
      - name: Ensure MySQL is started
        service: name=mysql state=started enabled=yes